### ISSUE TITLE
提个小小意见, a little suggest

### ISSUE THREAD

**Issue by asforest** [Server-Founder/NukkitLearn#3]
建议删除文件名中的*号，好像对windows不太友好，另外建议按每章将文章分类，直接放在根目录感觉有点杂乱
It is suggested to delete the * in the file name, which seems not very friendly to Windows. And a another suggested to categorize articles by chapter and put them directly in the root directory, which feels a bit messy

**Comment by MagicLu550** [comment]
感谢，我会做出修改的。另外我看到你发了一个pr，我刚刚发现。如果您想长期贡献的话，我可以把您拉入我们团队，并给予您直接提交的权限

**Comment by asforest** [comment]
有此想法，但生活中时间不是特别多，可能一到两个星期才能完成一篇文章，更新频率不会特别的频繁，谅解！

**Comment by MagicLu550** [comment]
> 有此想法，但生活中时间不是特别多，可能一到两个星期才能完成一篇文章，更新频率不会特别的频繁，谅解！

好的，没有关系，如果有这个想法可以随时联系我，感谢

**Comment by MagicLu550** [comment]
该问题已经解决
